simulation1:
	g++ -std=c++20 -I/localhost/packages/ublas/include -O3 -DNDEBUG -o s1 simulation1.cpp
simulation2:
	g++ -std=c++20 -I/localhost/packages/ublas/include -O3 -DNDEBUG -o s2 simulation2.cpp
simulation3:
	g++ -std=c++20 -I/localhost/packages/ublas/include -O3 -DNDEBUG -o s3 simulation3.cpp
estimation1:
	g++ -std=c++20 -I/localhost/packages/ublas/include -O3 -DNDEBUG -o e1 estimation1.cpp
estimation2:
	g++ -std=c++20 -I/localhost/packages/ublas/include -O3 -DNDEBUG -o e1 estimation2.cpp
